import { MAX_NPCS } from "../engine/limits.ts";

export const icon = (name: string, size = 18): string => {
  const paths: Record<string, string> = {
    arrow: '<path d="M5 12h14M13 6l6 6-6 6"/>',
    diagonal: '<path d="M6 18 18 6M6 6h12v12"/>',
    compass: '<circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5 5-3Z"/>',
    leaf: '<path d="M5 20 18 4M8 16C1 16 2 9 8 11l3 3m2-6C7 8 8 2 13 4l3 2m-2 8c1-6 8-6 7-2s-5 5-10 5"/>',
    code: '<path d="m8 6-6 6 6 6m8-12 6 6-6 6M14 3l-4 18"/>',
    map: '<path d="m3 5 6-2 6 3 6-2v15l-6 2-6-3-6 2V5Zm6-2v15m6-12v15"/>',
    users:
      '<circle cx="9" cy="8" r="3"/><path d="M3 21v-2a6 6 0 0 1 12 0v2m1-16a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/>',
    plus: '<path d="M12 5v14M5 12h14"/>',
    minus: '<path d="M5 12h14"/>',
    target: '<circle cx="12" cy="12" r="6"/><path d="M12 2v4m0 12v4M2 12h4m12 0h4"/>',
    sound: '<path d="m11 4-6 5H2v6h3l6 5V4Zm4 4a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',
    mute: '<path d="m11 4-6 5H2v6h3l6 5V4Zm5 5 6 6m0-6-6 6"/>',
    help: '<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 5 2c-2 1-2 2-2 3m0 3h.01"/>',
    crystal: '<path d="m12 2 7 8-7 12-7-12 7-8Zm0 0v20M5 10h14"/>',
    fire: '<path d="M12 2c3 5-2 6 1 10 2-1 3-3 3-5 8 8 4 15-4 15S1 14 7 8c0 3 2 4 3 5-1-5 3-7 2-11Z"/>',
    bolt: '<path d="m14 2-9 12h6l-1 8 9-12h-6l1-8Z"/>',
    sun: '<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',
    download: '<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
    close: '<path d="m6 6 12 12M6 18 18 6"/>',
    pause: '<path d="M8 5v14M16 5v14"/>',
    play: '<path d="m7 4 14 8-14 8V4Z"/>',
    github:
      '<path d="M9 19c-5 2-5-2-7-2m14 5v-4c0-1-.4-2-1-2 4-.4 7-2 7-6 0-2-1-3-2-4 .3-1 .3-3 0-4 0 0-2 0-4 2a14 14 0 0 0-8 0C6 2 4 2 4 2c-.3 1-.3 3 0 4-1 1-2 2-2 4 0 4 3 6 7 6-.6.5-1 1-1 2v4"/>',
    flag: '<path d="M5 22V3m0 0c5-4 9 4 15 0v11c-6 4-10-4-15 0"/>',
    settings:
      '<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="#1b2d20"/><circle cx="15" cy="17" r="3" fill="#1b2d20"/>',
    expand: '<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',
    collapse: '<path d="M3 8h5V3m13 5h-5V3M8 21v-5H3m13 5v-5h5"/>',
  };
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] ?? paths.leaf}</svg>`;
};
export function mountUI(): void {
  document.querySelector<HTMLDivElement>("#app")!.innerHTML = `
  <header class="topbar">
    <a class="brand" href="/" aria-label="Fern home"><span class="brand-mark">${icon("leaf", 29)}</span><span class="brand-name">fern<span class="brand-dot">.</span></span><span class="brand-caption">A WORLD ENGINE<br>BUILT FOR AGENTS</span></a>
    <nav class="tabs" aria-label="Workspace"><button class="tab active" data-view="world" aria-pressed="true">${icon("compass")}<span>World</span></button><button class="tab" data-view="atlas" aria-pressed="false">${icon("map")}<span>Atlas</span></button><button class="tab" data-view="lab" aria-pressed="false">${icon("code")}<span>Agent lab</span></button></nav>
    <div class="top-actions"><span class="live-label"><i class="live-dot"></i>All systems growing</span><a class="icon-button source-link" href="https://github.com/michaelcrosato/gpt61sol2daige" target="_blank" rel="noreferrer" aria-label="View source on GitHub">${icon("github", 20)}</a><button class="icon-button journal-toggle" id="journal-toggle" aria-label="Toggle expedition journal">${icon("leaf", 21)}</button></div>
  </header>
  <main class="workspace">
    <section class="world-stage" aria-label="Interactive game world">
      <div class="stage-heading"><div class="location-name">${icon("compass", 16)}<span id="location">Mosslight Hollow</span><span class="location-tag">THE VERDANT FRONTIER</span></div><span class="coordinates" id="coordinates">−20, 34</span></div>
      <div class="viewport" id="viewport">
        <canvas id="world-canvas" tabindex="0" aria-label="Procedural forest game. Use WASD to move, Space to pulse, Shift to dash, and E to interact."></canvas>
        <div class="world-label"><span class="live-dot"></span><span>LIVE WORLD</span><span class="divider-dot">/</span><span id="seed-label">SEED 0142</span></div>
        <div class="view-tools"><button class="icon-button" id="zoom-in" aria-label="Zoom in">${icon("plus")}</button><span id="zoom-value">1.8×</span><button class="icon-button" id="zoom-out" aria-label="Zoom out">${icon("minus")}</button><span class="tool-divider"></span><button class="icon-button" id="recenter" aria-label="Follow your traveler">${icon("target")}</button></div>
        <div class="welcome" id="welcome"><div class="eyebrow">A NEW PATH AWAITS</div><h1>Go where the<br><em>green grows.</em></h1><p>A living world, made from a seed.<br>Take a lantern. Bring a little company.</p><button class="primary-button" id="begin">Begin wandering ${icon("diagonal", 18)}</button><button class="text-button" id="continue" hidden>Continue your saved trail ${icon("arrow", 15)}</button></div>
        <div class="trail-note" id="trail-note" hidden><span>${icon("leaf", 17)}</span><div>Make yourself a little lost.<small>Follow the wisps. Light the old beacons.</small></div></div>
        <div class="minimap-shell"><canvas id="minimap" width="128" height="128" aria-label="Local terrain minimap"></canvas><span class="map-north">N</span><button class="map-open" id="open-map" aria-label="Open world atlas">${icon("map", 14)}</button></div>
        <div class="hotbar" aria-label="Traveler abilities"><button class="ability active" id="lantern" title="Toggle lantern (1)" aria-label="Toggle lantern" aria-pressed="true"><kbd>1</kbd>${icon("fire", 22)}<span>Lantern</span></button><button class="ability" id="pulse" title="Light pulse (Space)" aria-label="Light pulse"><kbd>2</kbd>${icon("sun", 22)}<span>Pulse</span></button><button class="ability" id="dash" title="Dash (Shift)" aria-label="Dash"><kbd>3</kbd>${icon("bolt", 22)}<span>Dash</span></button><span class="hotbar-divider"></span><div class="energy"><span>SPIRIT</span><div class="energy-track"><i id="energy-fill"></i></div></div></div>
        <div class="input-hints"><span><kbd>W A S D</kbd> move</span><span><kbd>E</kbd> interact</span><span class="scroll-hint">scroll to roam further</span></div>
        <div class="touch-controls" aria-label="Touch movement"><button data-move="0,-1" aria-label="Move north">↑</button><button data-move="-1,0" aria-label="Move west">←</button><button data-move="0,1" aria-label="Move south">↓</button><button data-move="1,0" aria-label="Move east">→</button><button id="touch-interact" aria-label="Interact">E</button></div>
        <div class="pause-label" id="pause-label" hidden>Simulation paused <span>Explore the state in Agent lab</span></div>
        <section class="alternate-view atlas-view" id="atlas-view" hidden aria-label="World atlas"><div class="view-heading"><div><span class="eyebrow">CHART YOUR OWN COURSE</span><h2>The world is wider.</h2><p>Click the map to mark a destination. Your trail starts wherever you are.</p></div><button class="secondary-button" id="atlas-back">Back to the trail ${icon("arrow", 16)}</button></div><div class="atlas-frame"><canvas id="atlas-canvas" width="900" height="600" aria-label="World atlas; click to mark a waypoint"></canvas><div class="atlas-compass">N<br>↑</div><span class="atlas-scale">384 m ━━━━━</span></div><div class="atlas-legend"><span><i style="background:#486747"></i>Meadow</span><span><i style="background:#304f39"></i>Woodland</span><span><i style="background:#34666a"></i>Water</span><span>${icon("crystal", 13)}Ancient beacon</span><span id="waypoint-label">No trail marker yet</span></div></section>
        <section class="alternate-view lab-view" id="lab-view" hidden aria-label="Agent development lab"><div class="view-heading"><div><span class="eyebrow">OBSERVE · ACT · VERIFY</span><h2>A world you can reason about.</h2><p>The same simulation, through a small, deterministic command surface.</p></div><span class="version-tag">ENGINE v1.1</span></div>
        <div class="lab-metrics"><div><span>SIMULATION TICK</span><strong id="lab-tick">0</strong></div><div><span>STATE CHECKSUM</span><strong id="lab-hash">—</strong></div><div><span>PHYSICS / TICK</span><strong id="lab-physics">—</strong></div><div><span>RESIDENT CHUNKS</span><strong id="lab-chunks">—</strong></div></div>
        <div class="lab-grid"><div class="lab-panel"><div class="panel-heading">World parameters <span>01</span></div><label class="field-label" for="world-seed">WORLD SEED</label><div class="input-row"><input id="world-seed" type="number" min="0" max="4294967295" value="142" /><button class="secondary-button" id="apply-seed">Regenerate</button></div><p class="field-help">Regenerates terrain and starts a fresh expedition.</p><label class="field-label" for="population">ACTIVE CREATURES <span id="population-label">2,400</span></label><input id="population" type="range" min="0" max="${MAX_NPCS}" step="1" value="2400" /><div class="range-labels"><span>0</span><span>${MAX_NPCS.toLocaleString()}</span></div><label class="check-row"><input id="debug-overlay" type="checkbox" /> Show chunk and collision bounds</label><label class="field-label" for="daytime">ATMOSPHERE</label><input id="daytime" type="range" min="0.38" max="1" step="0.01" value="0.38" /><div class="range-labels"><span>Afternoon</span><span>Moonlight</span></div></div>
        <div class="lab-panel"><div class="panel-heading">Simulation controls <span>02</span></div><div class="control-grid"><button class="secondary-button" id="pause">${icon("pause", 15)}Pause</button><button class="secondary-button" id="step">${icon("play", 15)}Step 60 ticks</button><button class="secondary-button" id="save">${icon("download", 15)}Save trail</button><button class="secondary-button" id="load">${icon("compass", 15)}Load trail</button><button class="secondary-button" id="snapshot">${icon("download", 15)}Snapshot JSON</button><button class="secondary-button" id="replay">${icon("download", 15)}Replay JSON</button></div><div class="lab-note">${icon("code", 18)}<p>Headless by design.<br><code>npm run agent</code> accepts the same JSON commands over stdin.</p></div><a class="text-button doc-link" href="/docs/agent-protocol.html" target="_blank" rel="noreferrer">Read the agent protocol ${icon("diagonal", 14)}</a></div>
        <div class="lab-panel command-panel"><div class="panel-heading">Command console <span>03</span></div><label class="sr-only" for="command-input">Agent JSON command</label><textarea id="command-input" spellcheck="false">{"op":"observe"}</textarea><div class="console-actions"><span>JSON in. Evidence out.</span><button class="primary-button small" id="run-command">Run command ${icon("arrow", 15)}</button></div><pre id="command-output" aria-live="polite">Ready. Try {"op":"describe"} for the full command schema.</pre></div></div></section>
      </div>
    </section>
    <aside class="sidebar" id="sidebar" aria-label="Expedition journal"><div class="chapter"><span class="eyebrow">THE VERDANT FRONTIER <span>01</span></span><h2>A small light.<br>A vast world.</h2><p>Somewhere beyond the canopy,<br>the old beacons are waiting.</p><div class="chapter-illustration">${icon("leaf", 58)}<span>Follow your curiosity.</span></div></div>
    <div class="party-section"><div class="section-label">YOUR EXPEDITION <span id="party-count">1 / 8</span></div><div class="traveler"><div class="avatar">${icon("compass", 23)}</div><div><strong id="traveler-name">You, the wayfarer</strong><span id="session-status">A little solitude</span></div><i class="live-dot"></i></div><button class="invite-button" id="invite">${icon("users", 17)}Invite a friend<span>+</span></button><button class="text-button join-link" id="join-open">Have an invite? Join an expedition ${icon("arrow", 14)}</button></div>
    <div class="journal"><div class="section-label">A REASON TO WANDER <span>${icon("flag", 14)}</span></div><div class="quest-title">Light the old beacons <span id="beacon-count">0 / 3</span></div><p class="quest-description">Gather light from the wisps. Carry three shards to each sleeping beacon.</p><div class="beacon-list"><button class="beacon-row" data-beacon="north"><span class="beacon-symbol">${icon("crystal", 19)}</span><span><strong>The Elder Grove</strong><small>Northeast · <b id="distance-north">1.2 km</b></small></span><span class="beacon-check" id="check-north">↗</span></button><button class="beacon-row" data-beacon="west"><span class="beacon-symbol">${icon("crystal", 19)}</span><span><strong>Whispering Stones</strong><small>Northwest · <b id="distance-west">1.2 km</b></small></span><span class="beacon-check" id="check-west">↗</span></button><button class="beacon-row" data-beacon="south"><span class="beacon-symbol">${icon("crystal", 19)}</span><span><strong>Stillwater Reach</strong><small>Southeast · <b id="distance-south">1.4 km</b></small></span><span class="beacon-check" id="check-south">↗</span></button></div><div class="satchel"><span>${icon("crystal", 18)}Light in your satchel</span><strong id="shard-count">0</strong></div></div>
    <div class="sidebar-footer"><span class="tiny-leaf">${icon("leaf", 15)}</span><p>Every leaf, every note, every path.<br><strong>Grown from code.</strong></p><span class="generation-mark">∞</span></div></aside>
  </main>
  <footer class="engine-strip"><div class="engine-alive"><span class="live-dot"></span><span>THE WORLD IS ALIVE</span></div><div class="stat"><strong id="stat-npcs">2,400</strong><span>creatures</span></div><div class="stat"><strong id="stat-fps">60</strong><span>fps</span></div><div class="stat"><strong id="stat-chunks">0</strong><span>chunks</span></div><div class="footer-note">A seed. A system. A thousand stories.</div><button class="sound-button" id="sound" aria-label="Enable sound" aria-pressed="false">${icon("mute", 17)}<span>Sound off</span></button><button class="icon-button" id="help" aria-label="Controls and help">${icon("help", 18)}</button></footer>
  <div id="toast" role="status" aria-live="polite" hidden></div>
  <dialog id="session-dialog"><form method="dialog"><button class="dialog-close icon-button" aria-label="Close expedition dialog">${icon("close", 20)}</button></form><div class="dialog-symbol">${icon("users", 28)}</div><span class="eyebrow">BETTER WITH A LITTLE COMPANY</span><h2>Share the trail.</h2><p>Up to eight travelers. One living world.<br>The host keeps the expedition open.</p><div id="session-create"><button class="primary-button full" id="host-room">Open an expedition ${icon("arrow", 18)}</button><div class="or-line"><span>or follow a friend</span></div></div><div id="room-share" hidden><label class="field-label" for="invite-link">YOUR INVITE LINK</label><div class="input-row"><input id="invite-link" readonly /><button class="secondary-button" id="copy-link">Copy</button></div><button class="text-button" id="leave-room">Leave expedition</button></div><div id="join-form"><label class="field-label" for="room-code">INVITE LINK OR ROOM CODE</label><input id="room-code" placeholder="Paste a friend's invite" autocomplete="off" /><button class="secondary-button full" id="join-room">Join expedition ${icon("arrow", 16)}</button></div><p id="network-message" class="network-message" role="status"></p><p class="network-footnote">Direct browser-to-browser play. Keep the host tab active; closing it ends the shared session.</p></dialog>
  <dialog id="help-dialog"><form method="dialog"><button class="dialog-close icon-button" aria-label="Close help">${icon("close", 20)}</button></form><span class="eyebrow">A FIELD GUIDE</span><h2>Take the long way.</h2><p>Find wisps, gather light, and wake the three ancient beacons. There is no timer.</p><div class="help-grid"><kbd>W A S D / ↑ ↓ ← →</kbd><span>Wander</span><kbd>SPACE / 2</kbd><span>Pulse near wisps to gather light</span><kbd>SHIFT / 3</kbd><span>Dash (uses spirit)</span><kbd>E</kbd><span>Collect crystals / light a beacon</span><kbd>1</kbd><span>Toggle your lantern</span><kbd>SCROLL / + −</kbd><span>Zoom from a leaf to a landscape</span><kbd>RIGHT DRAG</kbd><span>Pan the camera</span><kbd>F</kbd><span>Return to your traveler</span><kbd>M</kbd><span>Open your atlas</span><kbd>G / ESC</kbd><span>Enter / leave fullscreen game mode</span></div><p class="help-small">Save your trail in Agent lab. The lab also exposes the live simulation, world seed, NPC population, snapshots, and deterministic replay.</p><button class="primary-button full" id="help-done">The trail is calling ${icon("arrow", 18)}</button></dialog>
  `;
}
